debian - init service + config paths patch

diff --git a/debian/libbitcoin-server.init b/debian/libbitcoin-server.init
--- a/debian/libbitcoin-server.init
+++ b/debian/libbitcoin-server.init
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 ### BEGIN INIT INFO
-# Provides:	  libbitcoin
+# Provides:	  libbitcoin-server
 # Required-Start:    $local_fs $remote_fs $network $syslog $named
 # Required-Stop:     $local_fs $remote_fs $network $syslog $named
 # Default-Start:     2 3 4 5
@@ -10,131 +10,145 @@
 # Description:       starts libbitcoin-server using start-stop-daemon
 ### END INIT INFO
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/sbin/nginx
-NAME=nginx
-DESC=nginx
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
 
-# Include libbitcoin-server defaults if available
-if [ -r /etc/default/libbitcoin-server ]; then
-	. /etc/default/libbitcoin-server
-fi
+# Define LSB log_* functions.
+. /lib/lsb/init-functions
+
+PATH=/sbin:/bin:/usr/sbin:/usr/bin
+DAEMON=/usr/sbin/bs
+DAEMON_USER=libbitcoin
+NAME=bs
+DESC="libbitcoin-server daemon"
+BSLOGDIR=/var/log/libbitcoin
+BSPIDDIR=/var/run/libbitcoin
+PIDFILE=$BSPIDDIR/$NAME.pid
+DEFAULTSFILE=/etc/default/libbitcoin-server
+WAITFORDAEMON=60
+DEFAULT_ARGS=""
+ARGS=""
 
 test -x $DAEMON || exit 0
 
-. /lib/init/vars.sh
-. /lib/lsb/init-functions
-
-# Try to extract nginx pidfile
-PID=$(cat /etc/nginx/nginx.conf | grep -Ev '^\s*#' | awk 'BEGIN { RS="[;{}]" } { if ($1 == "pid") print $2 }' | head -n1)
-if [ -z "$PID" ]
-then
-	PID=/run/nginx.pid
+# Include libbitcoin-server defaults if available
+if [ -f $DEFAULTSFILE ]; then
+	. $DEFAULTSFILE
 fi
 
-#
-# Function that starts the daemon/service
-#
-do_start()
-{
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON -- \
-		$DAEMON_OPTS 2>/dev/null \
-		|| return 2
-}
-
-#
-# Function that stops the daemon/service
-#
-do_stop()
-{
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PID --name $NAME
-	RETVAL="$?"
-
-	sleep 1
-	return "$RETVAL"
-}
-
-#
-# Function that sends a SIGHUP to the daemon/service
-#
-do_reload() {
-	start-stop-daemon --stop --signal HUP --quiet --pidfile $PID --name $NAME
-	return 0
-}
-
-#
-# Rotate log files
-#
-do_rotate() {
-	start-stop-daemon --stop --signal USR1 --quiet --pidfile $PID --name $NAME
-	return 0
+wait_for_deaddaemon () {
+    pid=$1
+    sleep 1
+    if test -n "$pid"
+    then
+        if kill -0 $pid 2>/dev/null
+        then
+            cnt=0
+            while kill -0 $pid 2>/dev/null
+            do
+                cnt=`expr $cnt + 1`
+                if [ $cnt -gt $WAITFORDAEMON ]
+                then
+                    log_action_end_msg 1 "still running"
+                    exit 1
+                fi
+                sleep 1
+                [ "`expr $cnt % 3`" != 2 ] || log_action_cont_msg ""
+            done
+        fi
+    fi
+    log_action_end_msg 0
 }
 
 case "$1" in
 	start)
-		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-		do_start
-		case "$?" in
-			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-		esac
-		;;
+        if [ "$RUN_DAEMON" != "yes" ]; then
+            log_action_msg "Not starting $DESC (Disabled in $DEFAULTSFILE)."
+            exit 0
+        fi
+
+        log_action_begin_msg "Starting $DESC"
+
+        if start-stop-daemon --stop --signal 0 --quiet --pidfile $PIDFILE --exec $DAEMON; then
+            log_action_end_msg 0 "already running"
+        else
+            if start-stop-daemon --start --quiet --background --pidfile $PIDFILE --make-pidfile -c $DAEMON_USER --exec $DAEMON -- $DEFAULT_ARGS $ARGS
+            then
+                log_action_end_msg 0
+            else
+                log_action_end_msg 1
+                exit 1
+            fi
+        fi
+        ;;
 	stop)
-		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-		do_stop
-		case "$?" in
-			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-		esac
-		;;
+        log_action_begin_msg "Stopping $DESC"
+        pid=`cat $PIDFILE 2>/dev/null` || true
+
+        if test ! -f $PIDFILE -o -z "$pid"; then
+            log_action_end_msg 0 "not running - there is no $PIDFILE"
+            exit 0
+        fi
+
+        if start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON; then
+            wait_for_deaddaemon $pid
+        elif kill -0 $pid 2>/dev/null; then
+            log_action_end_msg 1 "Is $pid not $NAME?  Is $DAEMON a different binary now?"
+            exit 1
+        else
+            log_action_end_msg 1 "$DAEMON died: process $pid not running; or permission denied"
+            exit 1
+        fi
+        ;;
+    reload|force-reload)
+        log_action_begin_msg "Reloading $DESC configuration"
+        pid=`cat $PIDFILE 2>/dev/null` || true
+  
+        if test ! -f $PIDFILE -o -z "$pid"; then
+            log_action_end_msg 1 "not running - there is no $PIDFILE"
+            exit 1
+        fi
+  
+        if start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON; then
+            log_action_end_msg 0
+        elif kill -0 $pid 2>/dev/null; then
+            log_action_end_msg 1 "Is $pid not $NAME?  Is $DAEMON a different binary now?"
+            exit 1
+        else
+            log_action_end_msg 1 "$DAEMON died: process $pid not running; or permission denied"
+            exit 1
+        fi
+        ;;
 	restart)
 		log_daemon_msg "Restarting $DESC" "$NAME"
 
-		do_stop
-		case "$?" in
-			0|1)
-				do_start
-				case "$?" in
-					0) log_end_msg 0 ;;
-					1) log_end_msg 1 ;; # Old process is still running
-					*) log_end_msg 1 ;; # Failed to start
-				esac
-				;;
-			*)
-				# Failed to stop
-				log_end_msg 1
-				;;
-		esac
+        $0 stop
+        sleep 1
+        $0 start
 		;;
-	reload|force-reload)
-		log_daemon_msg "Reloading $DESC configuration" "$NAME"
+      status)
+        if test ! -r $(dirname $PIDFILE); then
+            log_failure_msg "cannot read PID file $PIDFILE"
+            exit 4
+        fi
+        pid=`cat $PIDFILE 2>/dev/null` || true
+        if test ! -f $PIDFILE -o -z "$pid"; then
+            log_failure_msg "$NAME is not running"
+            exit 3
+        fi
+        if ps "$pid" >/dev/null 2>&1; then
+            log_success_msg "$NAME is running"
+            exit 0
+        else
+            log_failure_msg "$NAME is not running"
+            exit 1
+        fi
+        ;;
+    *)
+        log_action_msg "Usage: $0 {start|stop|restart|reload|force-reload|status}" >&2
+        exit 1
+        ;;
 
-		do_reload
-		log_end_msg $?
-		;;
-	status)
-		status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
-		;;
-	rotate)
-		log_daemon_msg "Re-opening $DESC log files" "$NAME"
-		do_rotate
-		log_end_msg $?
-		;;
-	*)
-		echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|rotate}" >&2
-		exit 3
-		;;
 esac
 
-:
+exit 0
